---
title: "Resume"
author: Kyle Tolliver
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
source("./site_libs/resume.R")
```

```{r render, eval=FALSE}
render_resume('resume')
```

Aside
====================================

Contact Info {#contact}
------------------------------------

```{r contact}
print_contact('resume')
```

Skills {#skills}
------------------------------------

```{r skill}
print_skills()
```

Disclaimer {#disclaimer}
------------------------------------

<!-- Member of [Tau Beta Pi](https://tbp.org) <br /> Engineering Honor Society <br /> Idaho Delta chapter at BYU-Idaho. -->

<!-- This resume was made with <br /> the R package [pagedown](https://github.com/rstudio/pagedown). -->

Main
====================================

Kyle Tolliver {#title}
------------------------------------

Experience {data-icon=briefcase}
------------------------------------

```{r work}
print_section_resume('experience')
print_resume_section('internship')
```

Education {data-icon=graduation-cap}
------------------------------------

### Bachelor of Science in Software Engineering

Brigham Young University - Idaho

N/A

2017 <br> | <br> 2020

- Graduated with 3.6 GPA and Tau Beta Pi Honors
- Minor: Computer Engineering and Data Science

Projects {data-icon=laptop}
------------------------------------

```{r projects}
print_resume_section('projects')
```